name: workflow
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
               cache: npm
            - run: make setup
            - run: make test
            - run: make lint
            - name: Hello from Hexlet
              uses: actions/hexlet-components/hello-from-hexlet-action@release
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
               SNYK_TOKEN: ${{ secrets.SNYK }}
