name: workflow
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                    node-version: '16.x'
                    cache: npm
            - uses: make setup
            - uses: make test
            - uses: make lint